### ISSUE TITLE
Missing deps

### ISSUE THREAD

**Issue by luisgustavomob** [thepeaklab/react-component-library-starter#1]
Hi man!

First of all, congrats for the project!

I've just started to play with it, and have noticed that:
- "Rollout" dep is missing from package.json, so build script is not working...
- storybook-static folder, should be included on .gitignore

**Comment by dennisschneider** [comment]
Hi! thanks for pointing this out. Upgraded packages. Added rollout to dev-dependencies & bumped storybook to v 6.0.22 👋
